apiVersion: v1
kind: Pod
metadata:
  name: kubia-gpu-node-aff
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: gpu
            operator: In
            values:
            - "true"
  containers:
  - image: k7d32/kubia
    name: kubia
