---
apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual-withno-default-resources
spec:
  containers:
    - image: k7d32/kubia
      name: kubia
      ports:
        - containerPort: 8080
          protocol: TCP

