apiVersion: v1
kind: Pod
metadata:
  name: limits-enforce
spec:
  containers:
  - image: busybox
    name: main
    command: ["dd", "if=/dev/zero", "of=/dev/null"]
    resources:
      requests:
        cpu: 2
        memory: 20Mi
