apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv-b
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: mongodb-b
    fsType: ext4
