apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kubia-exp
spec:
  replicas: 3
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
        - kubia
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
      - name: kubia
        image: k7d32/kubia
        ports:
        - containerPort: 8080
